import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import "./components/text/text.css"
import "./components/text_and_image/dropdown_text_img.css"
import "./components/forms/contact_form.css"
import "./components/text_and_image/text_left_img_right.css"
import "./components/navbar/navbar.css"
import "./components/carousel/carousel.css"
import "./components/cards/stacked_cards.css"
import "./components/0_required_base/base.css"
import "./components/banners/banners.css"
import "./components/text_and_image/text_image_float.css"
import "bootstrap/dist/css/bootstrap.min.css"
import BootstrapClient from "./components/0_required_base/bootstrap_js";
import Navbar from "./components/navbar/navbar"

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
       <BootstrapClient/>
        <div className="container-fluid p-0">
            <Navbar sections={['Home', 'Products', 'About', 'Contact']} style="modern"/>
            {children}
        </div>
       
      </body>
    </html>
  );
}
