import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import "./components/text/text.css"
import "./components/text_and_image/dropdown_text_img.css"
import "./components/forms/contact_form.css"
import "./components/text_and_image/text_left_img_right.css"
import "./components/navbar/navbar.css"
import "./components/carousel/carousel.css"
import "./components/cards/stacked_cards.css"
import "./components/0_required_base/base.css"
import "./components/banners/banners.css"
import "./components/text_and_image/image_contact_card.css"
import "./components/text_and_image/text_image_float.css"
import "bootstrap/dist/css/bootstrap.min.css"
import "./components/text_and_image/items_list_img.css"

import BootstrapClient from "./components/0_required_base/bootstrap_js";
import Navbar_Left from "./components/navbar/navbar_content_left";
import Navbar_categories_hover from "./components/navbar/navbar_categories_hover";
import NavbarCentered from "./components/navbar/navbar_content_centered";
import NavbarSearch from "./components/navbar/navbar_search";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

                   
const navCentered = ['Banners', 'Cards', '/cart.png', 'Text', 'Contact']  

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
       <BootstrapClient/>
        <div className="container-fluid p-0">
          
            <NavbarCentered nav_sections={navCentered} 
     
             style="modern"/>
     
            <div style={{height: '1vh'}}></div>
            {children}
        </div>
       
      </body>
    </html>
  );
}
